lib/aurora_asp_web/router.ex
defmodule AuroraASPWeb.Router do
  use AuroraASPWeb, :router

  import AuroraASPWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AuroraASPWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AuroraASPWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AuroraASPWeb do
  #   pipe_through :api
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", AuroraASPWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/personas/registro", UserRegistrationController, :new
    post "/personas/registro", UserRegistrationController, :create
    get "/personas/ingreso", UserSessionController, :new
    post "/personas/ingreso", UserSessionController, :create
    get "/personas/recuperar", UserResetPasswordController, :new
    post "/personas/recuperar", UserResetPasswordController, :create
    get "/personas/recuperar/:token", UserResetPasswordController, :edit
    put "/personas/recuperar/:token", UserResetPasswordController, :update
  end

  scope "/", AuroraASPWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/personas/preferencias", UserSettingsController, :edit
    put "/personas/preferencias", UserSettingsController, :update
    get "/personas/preferencias/confirmar_email/:token", UserSettingsController, :confirm_email

    get "/esfuerzos/nuevo", EffortController, :new
    get "/esfuerzos/:id/editar", EffortController, :edit

    live "/esfuerzos/:effort_id/asignaciones", AssignLive.Index, :index
    live "/esfuerzos/:effort_id/asignaciones/nuevo", AssignLive.Index, :new
    live "/esfuerzos/:effort_id/asignaciones/:assign_id/editar", AssignLive.Index, :edit

    live "/esfuerzos/:effort_id/asignaciones/:assign_id", AssignLive.Show, :show
    live "/esfuerzos/:effort_id/asignaciones/:assign_id/ver/editar", AssignLive.Show, :edit
    live "/esfuerzos/:effort_id/asignaciones/:assign_id/estado/actualizar", AssignLive.Show, :status_update
    live "/esfuerzos/:effort_id/asignaciones/:assign_id/estado/anular", AssignLive.Show, :status_cancel
  end

  scope "/", AuroraASPWeb do
    pipe_through [:browser]

    delete "/personas/salir", UserSessionController, :delete
    get "/personas/confirmar", UserConfirmationController, :new
    post "/personas/confirmar", UserConfirmationController, :create
    get "/personas/confirmar/:token", UserConfirmationController, :edit
    post "/personas/confirmar/:token", UserConfirmationController, :update

    live "/esfuerzos", EffortLive.Index, :index
    resources "/esfuerzos", EffortController, except: [:new, :edit, :index]
    get "/colaboradores", PersonController, :index

    get "/faq", PageController, :faq
    get "/glosario", PageController, :glossary
    get "/guia_como_postular_esfuerzo", PageController, :guide_effort_apply

  end
end

lib/aurora_asp_web/controllers/user_session_controller.ex
defmodule AuroraASPWeb.UserSessionController do
  use AuroraASPWeb, :controller

  alias AuroraASP.Persons
  alias AuroraASPWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Persons.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Credenciales inválidas")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Sesión finalizada con éxito")
    |> UserAuth.log_out_user()
  end
end

lib/aurora_asp_web/views/user_session_view.ex
defmodule AuroraASPWeb.UserSessionView do
  use AuroraASPWeb, :view
end

lib/aurora_asp_web/templates/user_session/new.html.heex
<div class="form-container">
  <div class="form-header">
    <h3 class="form-title">Ingreso usuario</h3>
    <p class="form-description">Ingresa para proponer y colaborar en esfuerzos</p>
  </div>

  <div class="form-body">

      <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
      <%= if @error_message do %>
        <div class="alert alert-danger">
          <p><%= @error_message %></p>
        </div>
      <% end %>

      <div class="form-group">
        <%= label f, :email, "Correo electrónico (*)", class: "form-label" %>
        <%= email_input f, :email, required: true, class: "form-input" %>
      </div>

      <div class="form-group">
        <%= label f, :password, "Contraseña (*)", class: "form-label" %>
        <%= password_input f, :password, required: true, class: "form-input" %>
      </div>

      <div class="form-group">
        <label class="md:w-2/3 block text-gray-500 font-bold">
          <%= checkbox f, :remember_me, class: "form-checkbox" %>

          <span class="form-label-inline text-sm">
            Recordarme por 60 días
          </span>
        </label>
      </div>

      <div class="form-group">
        <%= submit "Ingresar", class: "form-submit" %>
      </div>
    </.form>

  </div>
  <div class="form-footer">
    <%= link "Registrarme", to: Routes.user_registration_path(@conn, :new), class: "text-link" %>
    <span class="mx-1">/</span>
    <%= link "Olvidé mi contraseña", to: Routes.user_reset_password_path(@conn, :new), class: "text-link" %>
  </div>

</div>